import { ScrollView, StyleSheet, Text } from 'react-native';
import { theme } from '@/lib/theme';

/**
 * Plain-language Terms of Service + Privacy Policy for the MVP.
 * Have a lawyer review before App Store / Google Play submission.
 */
export default function Legal() {
  return (
    <ScrollView
      style={styles.root}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
    >
      <Text style={styles.h1}>Terms of Service</Text>
      <Text style={styles.updated}>Last updated: September 2026</Text>

      <Text style={styles.h2}>1. What Restore does</Text>
      <Text style={styles.p}>
        Restore uses artificial intelligence to enhance, repair, and restore
        photos you choose to process. Results are generated by AI models and
        may not be perfectly accurate — restored details are the AI's best
        reconstruction, not a perfect record of the original scene.
      </Text>

      <Text style={styles.h2}>2. Your photos</Text>
      <Text style={styles.p}>
        You keep all rights to your photos. By processing a photo you confirm
        you have the right to use it. Photos are sent to our AI processing
        provider solely to perform the restoration you requested.
      </Text>

      <Text style={styles.h2}>3. Subscriptions</Text>
      <Text style={styles.p}>
        Restore Pro is sold as an auto-renewing subscription (weekly or annual)
        or as a one-time lifetime purchase through the App Store or Google
        Play. Payment is charged to your store account. Subscriptions renew
        automatically unless cancelled at least 24 hours before the end of the
        current period. You can manage or cancel in your store account
        settings at any time.
      </Text>

      <Text style={styles.h2}>4. Acceptable use</Text>
      <Text style={styles.p}>
        Don't use Restore to create misleading imagery of real people or
        events, or to infringe anyone's rights. We may suspend accounts that
        abuse the service.
      </Text>

      <Text style={styles.h1}>Privacy Policy</Text>

      <Text style={styles.h2}>What we collect</Text>
      <Text style={styles.p}>
        • Photos you choose to restore (sent to our AI provider to process
        your request, then deleted per the provider's retention policy).{'\n'}
        • Purchase status (stored on your device to unlock Pro features).{'\n'}
        • Basic diagnostics if the app crashes.
      </Text>

      <Text style={styles.h2}>What we don't do</Text>
      <Text style={styles.p}>
        We don't sell your data, we don't use your photos for advertising, and
        we don't train models on your photos.
      </Text>

      <Text style={styles.h2}>Your control</Text>
      <Text style={styles.p}>
        You can delete your recent restorations and reset the app's local data
        anytime in Settings. To request deletion of anything else, contact us
        at the support email listed on our store page.
      </Text>

      <Text style={styles.h2}>Children</Text>
      <Text style={styles.p}>
        Restore is not directed at children under 13, and we don't knowingly
        collect their data.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    padding: 20,
    paddingBottom: 48,
  },
  h1: {
    fontSize: 24,
    fontWeight: '800',
    color: theme.colors.text,
    marginTop: 16,
  },
  h2: {
    fontSize: 17,
    fontWeight: '700',
    color: theme.colors.text,
    marginTop: 20,
  },
  updated: {
    fontSize: 13,
    color: theme.colors.muted,
    marginTop: 4,
  },
  p: {
    fontSize: 14,
    color: theme.colors.muted,
    lineHeight: 21,
    marginTop: 8,
  },
});
